name: Checkout PrestaShop and prepare config
description: Checkout PrestaShop and prepare config
inputs:
  repository_ref:
    description: Base branch/ref from the repository
    required: true
  ps_dir:
    description: Directory target
    required: true
  pr_number:
    description: Pull request Id
    required: false
  rebase_or_merge:
    required: false
    description: Rebase or merge the pull request
  backoffice_layout:
    description: Backoffice layout
    required: false

runs:
  using: "composite"
  steps:
    # Checkout PrestaShop
    - uses: actions/checkout@v3
      name: Checkout PrestaShop repository
      with:
        fetch-depth: 0
        repository: PrestaShop/PrestaShop
        path: ${{ inputs.ps_dir }}

    - name: Config git
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
      working-directory: ${{ inputs.ps_dir }}
      shell: bash

    # Get the PR
    - name: Get pull request
      if: inputs.pr_number != ''
      working-directory: ${{ inputs.ps_dir }}
      run: |
        git fetch origin pull/${{ inputs.pr_number }}/head:pr${{ inputs.pr_number }}
        git checkout pr${{ inputs.pr_number }}
      shell: bash

    - name: Rebase
      working-directory: ${{ inputs.ps_dir }}
      if: inputs.pr_number != '' && inputs.rebase_or_merge == 'rebase'
      run: |
        git fetch origin ${{ inputs.repository_ref }}:${{ inputs.repository_ref }}
        git rebase origin/${{ inputs.repository_ref }}
      shell: bash

    - name: Merge
      working-directory: ${{ inputs.ps_dir }}
      if: inputs.pr_number != '' && inputs.rebase_or_merge == 'merge'
      run: |
        git fetch origin ${{ inputs.repository_ref }}:${{ inputs.repository_ref }}
        git merge origin/${{ inputs.repository_ref }}
      shell: bash

    # Or simply get the branch/tag
    - name: Get ref from repository ${{ inputs.repository_ref }}
      if: inputs.pr_number == '' && inputs.rebase_or_merge == '' && inputs.repository_ref != 'develop'
      working-directory: ${{ inputs.ps_dir }}
      run: |
        git fetch origin ${{ inputs.repository_ref }}:${{ inputs.repository_ref }}
        git checkout ${{ inputs.repository_ref }}
      shell: bash

    # Workaround until https://github.com/PrestaShop/PrestaShop/issues/29813 is fixed
    - name: PrestaShop Configuration (Copy of Config API)
      if: startsWith(inputs.repository_ref, '8.1') || (inputs.repository_ref == 'develop')
      run: cp ./${{ inputs.ps_dir }}/app/config/security_test.yml ./${{ inputs.ps_dir }}/app/config/security_prod.yml
      shell: bash

    - name: Adapt Back Office layout
      if: inputs.backoffice_layout == 'symfony'
      working-directory: ${{ inputs.ps_dir }}
      run: |
        echo PS_FF_SYMFONY_LAYOUT=true >> .env
      shell: bash
