name: Build PrestaShop and export sources and SQL dump as artifacts
on:
  workflow_call:
    inputs:
      repository_ref:
        type: string
        description: Base branch/ref from the repository
        required: true
      php_version:
        type: string
        description: PHP version
        required: true
      node_version:
        type: string
        description: Node version
        required: true
      pr_number:
        type: string
        description: Pull request Id
        required: false
        default: ''
      ps_mode_dev:
        type: boolean
        description: Enable/Disable the developer mode
        required: false
        default: false
      rebase_or_merge:
        type: string
        required: false
        description: Rebase or merge the pull request
        default: ''
      backoffice_layout:
        type: string
        description: Backoffice layout
        required: false
        default: 'legacy'
      artifact_name:
        type: string
        description: Artifact name, used later for download
        required: false
        default: 'shop-artifacts'

jobs:
  build-shop-artifacts:
    runs-on: ubuntu-latest
    name: Build shop artifacts based on ${{ inputs.repository_ref }}
    env:
      # Input values
      PS_MODE_DEV: ${{ inputs.ps_mode_dev && '1' || '0' }}
      PS_DEV_MODE: ${{ inputs.ps_mode_dev && '1' || '0' }}
      PHP_VERSION: ${{ inputs.php_version }}
      NODE_VERSION: ${{ inputs.node_version }}
      VERSION: ${{ inputs.php_version }}-apache
      PS_DOMAIN: ${{ (startsWith(inputs.repository_ref, '8.0') || startsWith(inputs.repository_ref, '1.7')) && 'localhost:8001' || 'localhost:8002' }}
      PS_ENABLE_SSL: ${{ (startsWith(inputs.repository_ref, '8.0') || startsWith(inputs.repository_ref, '1.7')) && '0' || '1' }}
      ADMIN_PASSWD: ${{ startsWith(inputs.repository_ref, '1.7') && 'prestashop_demo' || 'Correct Horse Battery Staple' }}
      URL_FO: ${{ (startsWith(inputs.repository_ref, '8.0') || startsWith(inputs.repository_ref, '1.7')) && 'http://localhost:8001/' || 'https://localhost:8002/' }}
      # Fixed values
      DB_USER: root
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_PREFIX: tst_
      PS_DIR: 'my_prestashop'
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      PS_COUNTRY: fr
      PS_LANGUAGE: en
      ADMIN_MAIL: 'demo@prestashop.com'
      # Build assets and install shop
      PS_INSTALL_AUTO: 1
      DISABLE_MAKE: 0

    steps:
      - name: Print Inputs values
        shell: bash
        run: echo "${{ toJSON(inputs) }}"

      # Checkout repository to use custom actions
      - uses: actions/checkout@v3
        with:
          path: custom_actions

      - name: Checkout PrestaShop
        uses: ./custom_actions/.github/workflows/actions/checkout-prestashop
        with:
          repository_ref: ${{ inputs.repository_ref }}
          ps_dir: ${{ env.PS_DIR }}
          pr_number: ${{ inputs.pr_number }}
          rebase_or_merge: ${{ inputs.rebase_or_merge }}
          backoffice_layout: ${{ inputs.backoffice_layout }}

      # Pre pull/build images (when build background enabled)
      - name: Pull images in background
        working-directory: ${{ env.PS_DIR }}
        run: |
          # Pull mysql image
          USER_ID=$(id -u) GROUP_ID=$(id -g) nohup docker-compose -f docker-compose.yml pull -q mysql &> /dev/null &
      - name: Build PrestaShop image in background
        working-directory: ${{ env.PS_DIR }}
        run: |
          # Build prestashop image in background
          USER_ID=$(id -u) GROUP_ID=$(id -g) nohup docker-compose -f docker-compose.yml build prestashop-git &> /dev/null &

      # Run composer install before building the assets since the themes come from composer
      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "composer-cache-dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        working-directory: ${{ env.PS_DIR }}
        shell: bash
      - name: Restore composer cache dir
        uses: actions/cache/restore@v3
        id: composer-cache
        with:
          path: ${{ steps.composer-cache-dir.outputs.composer-cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      # Run composer install
      - name: Install Composer dependencies
        run: composer install --prefer-dist --optimize-autoloader
        working-directory: ${{ env.PS_DIR }}
        shell: bash
      # Save composer cache when it didn't exist
      - name: Save composer cache dir
        uses: actions/cache/save@v3
        if: steps.composer-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.composer-cache-dir.outputs.composer-cache-dir }}
          key: ${{ steps.composer-cache.outputs.cache-primary-key }}

      # Install node dependencies and build assets
      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Build assets in parallel and in background
        run: |
          (pushd ${{ env.PS_DIR }}/admin-dev/themes/new-theme; touch buildLock; npm ci; npm run build; rm buildLock; popd) &
          (pushd ${{ env.PS_DIR }}/admin-dev/themes/default; touch buildLock; npm ci; npm run build; rm buildLock; popd) &
          (pushd ${{ env.PS_DIR }}/themes/classic/_dev; touch buildLock; npm ci; npm run build; rm buildLock; popd) &
          (pushd ${{ env.PS_DIR }}/themes/; touch buildLock; npm ci; npm run build; rm buildLock; popd) &
        shell: bash

      # Certificate
      - name: Generate a certificate
        if: startsWith(inputs.repository_ref, '8.1') || inputs.repository_ref == 'develop'
        run: |
          ## Install MkCert
          sudo apt install libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
          ## Generate certificate
          mkcert -key-file ./${{ env.PS_DIR }}/.docker/ssl.key -cert-file ./${{ env.PS_DIR }}/.docker/ssl.crt localhost
          ## Link certificate to Chrome Trust Store
          mkdir -p $HOME/.pki/nssdb
          certutil -d $HOME/.pki/nssdb -N
          certutil -d sql:$HOME/.pki/nssdb -n localhost -A -t "TCu,Cu,Tu" -i ./${{ env.PS_DIR }}/.docker/ssl.crt
          ## Add self-signed certificate to Chrome Trust Store
          mkcert -install

      # Wait for all builds to be finished (the check is required because we encountered cases where the action exited before
      # everything was built, probably because of the parallelization and background processes)
      - name: Check that all asset builds are finished
        run: |
          buildLocks="admin-dev/themes/new-theme/buildLock admin-dev/themes/default/buildLock themes/classic/_dev/buildLock themes/buildLock"
          echo Checking for all these lock files $buildLocks
          for lockFile in $buildLocks; do
            lockFile="${{ env.PS_DIR }}/$lockFile"
            if [ -f $lockFile ]; then
              echo Wait for $lockFile to be removed
              sleep 1
              while [ -f $lockFile ]; do
                echo $lockFile still present wait a bit more
                sleep 1
              done
            fi
            echo $lockFile is no longer present
          done
        shell: bash

      # Create shop with Docker build assets, and initialize database and shop content
      - name: Start PrestaShop docker
        working-directory: ${{ env.PS_DIR }}
        timeout-minutes: 5
        env:
          URL_FO: ${{ ((startsWith(inputs.repository_ref, '8.0')) || (startsWith(inputs.repository_ref, '1.7'))) && 'http://localhost:8001/' || 'https://localhost:8002/' }}
          VERSION: ${{ (startsWith(inputs.repository_ref, '1.7')) && inputs.php_version || env.VERSION }}
          # Initial build, install shop data but assets are already built
          DISABLE_MAKE: 1
          PS_INSTALL_AUTO: 1
        run: |
          # First wait for all images to be ready
          echo Check that all images are ready
          until docker images | grep mysql; do echo Waiting for mysql image; sleep 1; done
          until docker images | grep prestashop-git; do echo Waiting for prestashop-git image; sleep 1; done
          # Then build and start the docker
          echo Build docker via docker composer
          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml up -d --build prestashop-git mysql
          echo Waiting for response from the FO ${{ env.URL_FO }}
          bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} ${{ env.URL_FO }}en/)" != "200" ]]; do sleep 1; done'

      # Prepare archive contents to share with following jobs
      - name: Archive shop content
        if: always()
        uses: ./custom_actions/.github/workflows/actions/archive-shop
        with:
          ps_dir: ${{ env.PS_DIR }}
          db_user: ${{ env.DB_USER }}
          db_password: ${{ env.DB_PASSWD }}
          db_name: ${{ env.DB_NAME }}
          artifact_name: ${{ inputs.artifact_name }}

      # Export logs in case of failure
      - name: Export docker logs
        if: failure()
        uses: ./custom_actions/.github/workflows/actions/export-docker-logs
        with:
          ps_dir: ${{ env.PS_DIR }}
          artifact_name: build-shop
