name: Testing PrestaShop upgrade
on:
  workflow_dispatch:
    inputs:
      upgrade_module_ref:
        description: Use a branch or tag for the autoupgrade module
        type: choice
        required: true
        options:
          - 'dev'
          - 'master'
          - '1.7.8.x'
          - 'v4.16.0'
          - 'v4.15.0'
          - 'v4.14.2'
        default: 'dev'
      source_ref:
        type: choice
        description: Use a source branch or tag to start the upgrade from
        required: true
        options:
          - '8.1.x'
          - '8.0.x'
          - '1.7.8.x'
          - '8.0.4'
          - '1.7.8.9'
        default: '1.7.8.x'
      target_ref:
        type: choice
        description: Use a target branch or tag to upgrade to
        required: true
        options:
          - 'develop'
          - '8.1.x'
          - '8.0.x'
          - '8.0.4'
          - '8.1.0-rc.1'
          - '8.1.0-build1'
        default: '8.1.x'
      use_nightly_build:
        type: boolean
        description: Use latest nightly matching the target branch, if not the branch is checkout from repository branch HEAD
        default: false
      target_version:
        description: If you do not use the nightly release, you must specify the version of target branch (ex 1.7.8.9, 8.0.4)
        type: string
        require: false
      php_version:
        type: choice
        description: PHP version
        required: true
        options:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        default: '8.1'
      node_version:
        type: choice
        description: Node version
        required: true
        options:
          - '14'
          - '16'
        default: '14'

jobs:
  manual_test_upgrade:
    uses: ./.github/workflows/upgrade_test_workflow_call.yml
    with:
      source_ref: ${{ github.event.inputs.source_ref }}
      target_ref: ${{ github.event.inputs.target_ref }}
      use_nightly_build: ${{ github.event.inputs.use_nightly_build }}
      target_version: ${{ github.event.inputs.target_version }}
      php_version: ${{ github.event.inputs.php_version }}
      node_version: ${{ github.event.inputs.node_version }}
