# This is a temporary workflow to force triggering the new manual one which is not usable as long as it's not on the default branch
name: Testing PrestaShop upgrade

on:
    push:

jobs:
    auto_test_autoupgrade:
        uses: ./.github/workflows/upgrade_test_workflow_call.yml
        with:
            source_ref: 8.0.4
            target_ref: 8.1.0-build1
            target_version: 8.1.0
            use_nightly_build: false
            php_version: 7.4
            node_version: 14
