name: Testing PrestaShop upgrade
on:
  workflow_call:
    inputs:
      source_branch:
        description: Use a source branch to start the upgrade from
        type: string
        required: true
      target_branch:
        description: Use a target branch to upgrade to
        type: string
        required: true
      php_version:
        description: PHP version
        type: string
        required: true
      node_version:
        description: Node version
        type: string
        required: true

jobs:
  # Pre-job : Get Upgrade target versions
  get_ps_nightly_target_version:
    name: Get Upgrade target versions
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          path: main

      - id: set-target-nightly-version
        name: Get target details from nightly last reports
        run: |
          echo Inputs "${{ toJSON(inputs) }}"
          echo target_version=$(php ./.github/scripts/get_version_from_nightly.php ${{ inputs.target_branch }}) >> $GITHUB_OUTPUT
        working-directory: main

      - name: Display nightly version
        shell: bash
        run: echo "${{ steps.set-target-nightly-version.outputs.target_version }}"
    outputs:
      target_version: ${{ steps.set-target-nightly-version.outputs.target_version }}

  testing-upgrade:
    runs-on: ubuntu-latest
    name: test
    needs: get_ps_nightly_target_version
    strategy:
      fail-fast: false
      matrix:
        TEST_COMMAND:
          - 'cldr'
          - 'functional:API'
          - 'functional:BO:login'
          - 'functional:BO:dashboard'
          - 'functional:BO:orders:01:0-1'
          - 'functional:BO:orders:01-create-orders'
          - 'functional:BO:orders:01-view-and-edit-order'
          - 'functional:BO:orders:02'
          - 'functional:BO:orders:03-05'
          - 'functional:BO:catalog:01-02'
          - 'functional:BO:catalog:03-04'
          - 'functional:BO:catalog:05-06'
          - 'functional:BO:catalog:07-08'
          - 'functional:BO:customer:01'
          - 'functional:BO:customer:02-03'
          - 'functional:BO:customer-service'
          - 'functional:BO:modules'
          - 'functional:BO:design'
          - 'functional:BO:shipping'
          - 'functional:BO:payment'
          - 'functional:BO:international:01'
          - 'functional:BO:international:02'
          - 'functional:BO:international:03-04'
          - 'functional:BO:shop-parameters:01-02'
          - 'functional:BO:shop-parameters:03-04'
          - 'functional:BO:shop-parameters:05-07'
          - 'functional:BO:advanced-parameters:01-06'
          - 'functional:BO:advanced-parameters:07-10'
          - 'functional:BO:header'
          - 'functional:FO:01-03'
          - 'functional:FO:04-07'
          - 'functional:FO:08-12'
          - 'functional:FO:classic:01-03'
          - 'functional:FO:classic:04-07'
          - 'functional:FO:classic:08-12'
          - 'functional:FO:hummingbird:01-03'
          - 'functional:productV2'
          - 'functional:WS'
          - 'modules'
          - 'regression'
          - 'sanity'
          - 'sanity:productV2'
        BASE_BRANCH:
          - ${{ inputs.target_branch }}
        exclude:
          ## 1.7.8.x
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'cldr'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:BO:dashboard'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:productV2'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:API'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:FO:classic:01-03'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:FO:classic:04-07'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:FO:classic:08-12'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:FO:hummingbird:01-03'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'functional:WS'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'modules'
          - BASE_BRANCH: 1.7.8.x
            TEST_COMMAND: 'sanity:productV2'
          ## 8.0.x
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'cldr'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:BO:dashboard'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:productV2'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:API'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:FO:classic:01-03'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:FO:classic:04-07'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:FO:classic:08-12'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:FO:hummingbird:01-03'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'functional:WS'
          - BASE_BRANCH: 8.0.x
            TEST_COMMAND: 'modules'
          ## 8.1.x
          - BASE_BRANCH: 8.1.x
            TEST_COMMAND: 'functional:FO:01-03'
          - BASE_BRANCH: 8.1.x
            TEST_COMMAND: 'functional:FO:04-07'
          - BASE_BRANCH: 8.1.x
            TEST_COMMAND: 'functional:FO:08-12'
          ## develop
          - BASE_BRANCH: develop
            TEST_COMMAND: 'functional:FO:01-03'
          - BASE_BRANCH: develop
            TEST_COMMAND: 'functional:FO:04-07'
          - BASE_BRANCH: develop
            TEST_COMMAND: 'functional:FO:08-12'

    env:
      SOURCE_BRANCH: ${{ inputs.source_branch }}
      PS_MODE_DEV: '0'
      PHP_VERSION: ${{ inputs.php_version }}
      NODE_VERSION: ${{ inputs.node_version }}
      PS_DIR: 'my_prestashop'
      ## Install PrestaShop & UI Tests
      VERSION: ${{ inputs.php_version }}-apache
      PS_INSTALL_AUTO: 1
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_SERVER: mysql
      DB_PREFIX: tst_
      PS_DOMAIN: ${{ ((inputs.source_branch == '8.0.x') || (inputs.source_branch == '1.7.8.x')) && 'localhost:8001' || 'localhost:8002' }}
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      PS_COUNTRY: fr
      PS_LANGUAGE: en
      PS_DEV_MODE: '0'
      PS_ENABLE_SSL: ${{ ((inputs.source_branch == '8.0.x') || (inputs.source_branch == '1.7.8.x')) && '0' || '1' }}
      ADMIN_MAIL: 'demo@prestashop.com'
      ADMIN_PASSWD: ${{ (inputs.source_branch == '1.7.8.x') && 'prestashop_demo' || 'Correct Horse Battery Staple' }}

    steps:
      - name: Print Inputs values
        shell: bash
        run: echo "${{ toJSON(inputs) }}"

      # Checkout PrestaShop source
      - uses: actions/checkout@v3
        name: Checkout PrestaShop repository with branch ${{ env.SOURCE_BRANCH }}
        with:
          fetch-depth: 0
          repository: PrestaShop/PrestaShop
          path: ${{ env.PS_DIR }}
          ref: ${{ env.SOURCE_BRANCH }}

      # Certificate
      - name: Generate a certificate
        if: (inputs.source_branch == '8.1.x') || (inputs.source_branch == 'develop')
        run: |
          ## Install MkCert
          sudo apt install libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
          ## Generate certificate
          mkcert -key-file ./${{ env.PS_DIR }}/.docker/ssl.key -cert-file ./${{ env.PS_DIR }}/.docker/ssl.crt localhost
          ## Link certificate to Chrome Trust Store
          mkdir -p $HOME/.pki/nssdb 
          certutil -d $HOME/.pki/nssdb -N 
          certutil -d sql:$HOME/.pki/nssdb -n localhost -A -t "TCu,Cu,Tu" -i ./${{ env.PS_DIR }}/.docker/ssl.crt
          ## Add self-signed certificate to Chrome Trust Store
          mkcert -install

      # Workaround until https://github.com/PrestaShop/PrestaShop/issues/29813 is fixed
      - name: PrestaShop Configuration (Copy of Config API)
        if: (env.BASE_BRANCH == '8.1.x') || (env.BASE_BRANCH == 'develop')
        run: cp ./${{ env.PS_DIR }}/app/config/security_test.yml ./${{ env.PS_DIR }}/app/config/security_prod.yml

      # Create shop with Docker
      - name: Build and run shop with docker
        working-directory: ${{ env.PS_DIR }}
        timeout-minutes: 15
        env:
          DISABLE_MAKE: 0
          URL_FO: ${{ ((inputs.source_branch == '8.0.x') || (inputs.source_branch == '1.7.8.x')) && 'http://localhost:8001/' || 'https://localhost:8002/' }}
          VERSION: ${{ (inputs.source_branch == '1.7.8.x') && inputs.php_version || env.VERSION }}
        run: |
          echo "    container_name: prestashop_autoupgrade" >> docker-compose.yml
          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml up -d --build
          bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} ${{ env.URL_FO }}en/)" != "200" ]]; do sleep 5; done'
          docker ps

      # Install upgrade module and run CLI upgrade
      -   uses: actions/checkout@v3
          name: Checkout Autoupgrade module
          with:
            fetch-depth: 0
            repository: PrestaShop/autoupgrade
            path: ${{ env.PS_DIR }}/modules/autoupgrade

      - name: Composer install in module
        run: composer install
        working-directory: ${{ env.PS_DIR }}/modules/autoupgrade

      - name: Install module via CLI commands
        run: docker exec -u www-data prestashop_autoupgrade php bin/console prestashop:module install autoupgrade

      - name: Upgrade shop to ${{ fromJson(needs.get_ps_nightly_target_version.outputs.target_version).version }} - ${{ fromJson(needs.get_ps_nightly_target_version.outputs.target_version).zip }}
        run: |
          docker exec -u www-data prestashop_autoupgrade mkdir admin-dev/autoupgrade/download
          docker exec -u www-data prestashop_autoupgrade curl -L ${{ fromJson(needs.get_ps_nightly_target_version.outputs.target_version).zip }} -o admin-dev/autoupgrade/download/prestashop.zip
          docker exec -u www-data prestashop_autoupgrade curl -L ${{ fromJson(needs.get_ps_nightly_target_version.outputs.target_version).xml }} -o admin-dev/autoupgrade/download/prestashop.xml
          echo "{\"channel\":\"archive\",\"archive_prestashop\":\"prestashop.zip\",\"archive_num\":\"${{ fromJson(needs.get_ps_nightly_target_version.outputs.target_version).version }}\", \"archive_xml\":\"prestashop.xml\", \"PS_AUTOUP_CHANGE_DEFAULT_THEME\":"0", \"skip_backup\": "1"}" > ${{ env.PS_DIR }}/modules/autoupgrade/config.json
          docker exec -u www-data prestashop_autoupgrade php modules/autoupgrade/cli-updateconfig.php --from=modules/autoupgrade/config.json --dir=admin-dev
          docker exec -u www-data prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php --dir="admin-dev" --action="compareReleases"
          docker exec -u www-data prestashop_autoupgrade php modules/autoupgrade/tests/testCliProcess.php modules/autoupgrade/cli-upgrade.php --dir=admin-dev

      # UI Tests : Setup, Install & Execute
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup NPM
        run: npm install -g npm@7

      # Checkout PrestaShop source
      - uses: actions/checkout@v3
        name: Checkout tests from target version ${{ inputs.target_branch }}
        with:
          fetch-depth: 0
          repository: PrestaShop/PrestaShop
          path: target_prestashop
          ref: ${{ inputs.target_branch }}

      - name: Clear UI tests from source branch and copy those from target
        shell: bash
        run: |
          rm -fR ${{ env.PS_DIR }}/tests/UI
          cp -R target_prestashop/tests/UI ${{ env.PS_DIR }}/tests/UI

      - name: Install tests dependencies
        run: npm install
        working-directory: ${{ env.PS_DIR }}/tests/UI

      - name: Run tests
        id: run_tests
        run: |
          export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
          npm run test:${{ matrix.TEST_COMMAND }}
        working-directory: ${{ env.PS_DIR }}/tests/UI
        env:
          URL_FO: ${{ ((inputs.base_branch == '8.0.x') || (inputs.base_branch == '1.7.8.x')) && 'http://localhost:8001/' || 'https://localhost:8002/' }}
          DB_NAME: prestashop
          DB_PASSWD: prestashop
          HEADLESS: true
          ENABLE_SSL: true
          TAKE_SCREENSHOT_AFTER_FAIL: true
          SMTP_SERVER: '172.17.0.1'

      # UI Tests : Upload screenshots
      - run: echo "SCREENSHOT_CAMPAIGN=$( echo -e '${{ matrix.TEST_COMMAND }}' | tr ':' '-' )" >> $GITHUB_ENV
        if: ${{ always() }}

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshots-${{ env.SCREENSHOT_CAMPAIGN }}
          path: '${{ env.PS_DIR }}/tests/UI/screenshots/'
