name: Testing PrestaShop upgrade
on:
  workflow_dispatch:
    inputs:
      source_branch:
        type: choice
        description: Use a source branch to start the upgrade from
        required: true
        options:
          - '8.1.x'
          - '8.0.x'
          - '1.7.8.x'
        default: '1.7.8.x'
      #source_version:
      #  type: string
      #  description: OR define a released version (ex 1.7.8.3) to start the upgrade from (ignored if left empty)
      #  required: false
      target_branch:
        type: choice
        description: Use a target branch to upgrade to
        required: true
        options:
          - 'develop'
          - '8.1.x'
          - '8.0.x'
        default: '8.0.x'
      # LATER, can include a PR from the core to test an autoupgrade debug, we may need to build a release archive from the PR
      #target_pr_number:
      #  description: Pull request Id
      #  required: true
      # LATER, handle a specific version and build the source based on the existing release archives or github tags
      use_nightly_build:
        type: boolean
        description: Use latest nightly matching the source/target branches, if not the branches are checkout from repository branch HEAD
        default: false
      php_version:
        type: choice
        description: PHP version
        required: true
        options:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
        default: '8.1'
      node_version:
        type: choice
        description: Node version
        required: true
        options:
          - '14'
          - '16'
        default: '14'

jobs:
  manual_test_upgrade:
    uses: ./.github/workflows/upgrade_test_workflow_call.yml
    with:
      source_branch: ${{ github.event.inputs.source_branch }}
      target_branch: ${{ github.event.inputs.target_branch }}
      php_version: ${{ github.event.inputs.php_version }}
      node_version: ${{ github.event.inputs.node_version }}
